name: CI
on: push

jobs:
  setup-version:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    env:
      VERSION: 1.0.0.1
    outputs:
      rc_version: ${{ steps.step1.outputs.rc_version }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: set-version
        run: echo "::set-output name=rc_version::${VERSION}"
      - id: step2
        run: echo "::set-output name=test::world"
      - run: echo "Hihi ${{steps.set-version.outputs.rc_version}}"
  job2:
    runs-on: ubuntu-latest
    needs: setup-version
    steps:
      - run: echo ${{needs.setup-version.outputs.rc_version}} ${{needs.setup-version.outputs.output2}}
